version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3305:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=personal_website
  redis:
    container_name: redis
    hostname: redis
    image: redis:7.0.8
    restart: always
    ports:
      - 6379:6379
    command: 
      --requirepass "123456"
    privileged: true
    volumes:
      - /Users/hcm-b0361/redis/data:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379:0:123456
    ports:
    - "8081:8081"
