version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - /var/lib/docker/volumes/pgdata/_data:/var/lib/postgresql/data
