basePath: /
definitions:
  request.LoginForm:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  request.RegisterForm:
    properties:
      avatar:
        type: string
      email:
        type: string
      gender:
        type: integer
      nickname:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
info:
  contact: {}
  description: personal-website API
  title: personal-website API
  version: 1.0.0
paths:
  /user/info:
    get:
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{"avatar":"", "email":"", "nickname":"",
            "id":"1"},"msg":"操作成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 获取玩家信息
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 账号
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.LoginForm'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{"token":"xxxxxxxxx"},"msg":"获取成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 登陆
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 账号
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.RegisterForm'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{"token":"xxxxxxxxx"},"msg":"获取成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 注册
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
