basePath: /
definitions:
  request.LoginForm:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    type: object
info:
  contact: {}
  description: personal-website API
  title: personal-website API
  version: 1.0.0
paths:
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 账号
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.LoginForm'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{"token":"xxxxxxxxx"},"msg":"获取成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 静默登陆
      tags:
      - merchant
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
